/* ============================================================
   AwaAgent - Icon registry
   Maps the design's semantic icon names to Hugeicons (free set),
   so the whole app references icons by intent (e.g. "wallet")
   rather than importing icon objects everywhere.
   ============================================================ */

import {
  Search01Icon,
  Home01Icon,
  Calendar01Icon,
  Shield01Icon,
  CheckmarkBadge01Icon,
  Wallet01Icon,
  Bookmark01Icon,
  User02Icon,
  Location01Icon,
  BedIcon,
  Bathtub01Icon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  Tick01Icon,
  LockIcon,
  Key01Icon,
  FilterHorizontalIcon,
  Cancel01Icon,
  ArrowDown01Icon,
  Navigation03Icon,
  InformationCircleIcon,
  Alert02Icon,
  SparklesIcon,
  EyeIcon,
  StarIcon,
  Add01Icon,
  MinusSignIcon,
  Invoice01Icon,
  CrownIcon,
  Clock01Icon,
  FlashIcon,
  Copy01Icon,
  Building01Icon,
  DashboardSquare01Icon,
  Call02Icon,
  Mail01Icon,
  Gps01Icon,
  RefreshIcon,
  Logout01Icon,
  ArrowDataTransferHorizontalIcon,
  MapsGlobal01Icon,
  Cash01Icon,
  Upload01Icon,
  BubbleChatIcon,
  GiftIcon,
  Menu01Icon,
  Notification01Icon,
  Settings01Icon,
  Analytics01Icon,
  UserGroupIcon,
  Coins01Icon,
  CreditCardIcon,
  Chart01Icon,
  Door01Icon,
  DocumentValidationIcon,
  JusticeScale01Icon,
  PauseIcon,
  CancelCircleIcon,
  DollarCircleIcon,
  ArrowUpRight01Icon,
} from "@hugeicons/core-free-icons";

// Hugeicons icon objects are arrays of svg child tuples.
export type IconData = readonly (readonly [string, Record<string, string | number>])[];

export const ICONS = {
  explore: Search01Icon,
  search: Search01Icon,
  home: Home01Icon,
  calendar: Calendar01Icon,
  shield: Shield01Icon,
  shieldCheck: CheckmarkBadge01Icon,
  wallet: Wallet01Icon,
  bookmark: Bookmark01Icon,
  user: User02Icon,
  pin: Location01Icon,
  bed: BedIcon,
  bath: Bathtub01Icon,
  arrowR: ArrowRight01Icon,
  arrowL: ArrowLeft01Icon,
  check: Tick01Icon,
  lock: LockIcon,
  key: Key01Icon,
  filter: FilterHorizontalIcon,
  close: Cancel01Icon,
  chevR: ArrowRight01Icon,
  chevD: ArrowDown01Icon,
  nav: Navigation03Icon,
  info: InformationCircleIcon,
  alert: Alert02Icon,
  spark: SparklesIcon,
  eye: EyeIcon,
  star: StarIcon,
  plus: Add01Icon,
  minus: MinusSignIcon,
  receipt: Invoice01Icon,
  crown: CrownIcon,
  clock: Clock01Icon,
  bolt: FlashIcon,
  copy: Copy01Icon,
  building: Building01Icon,
  grid: DashboardSquare01Icon,
  phone: Call02Icon,
  mail: Mail01Icon,
  gps: Gps01Icon,
  refresh: RefreshIcon,
  logout: Logout01Icon,
  swap: ArrowDataTransferHorizontalIcon,
  map: MapsGlobal01Icon,
  cash: Cash01Icon,
  upload: Upload01Icon,
  chat: BubbleChatIcon,
  gift: GiftIcon,
  menu: Menu01Icon,
  bell: Notification01Icon,
  settings: Settings01Icon,
  analytics: Analytics01Icon,
  users: UserGroupIcon,
  coins: Coins01Icon,
  card: CreditCardIcon,
  chartBar: Chart01Icon,
  door: Door01Icon,
  logs: DocumentValidationIcon,
  scale: JusticeScale01Icon,
  pause: PauseIcon,
  ban: CancelCircleIcon,
  dollar: DollarCircleIcon,
  trend: ArrowUpRight01Icon,
} as const;

export type IconName = keyof typeof ICONS;
